//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBoxSolutions
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AlbumLibrary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlbumLibrary()
        {
            this.SongLibraries = new HashSet<SongLibrary>();
        }

        public int AlbumId { get; set; }
        public string AlbumName { get; set; }
        public byte[] CoverArt { get; set; }
        public string MusicBrainzId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> NumTracks { get; set; }
        public bool isVerified { get; set; }
        public bool hasMusicBrainzUpdate { get; set; }
        public string iTunesId { get; set; }
        public bool hasiTunesUpdate { get; set; }
        public bool isHidden { get; set; }
        public bool isFavourite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongLibrary> SongLibraries { get; set; }
    }
}
