//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBoxSolutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryView
    {
        public int TrackId { get; set; }
        public string Type { get; set; }
        public Nullable<int> SongId { get; set; }
        public string SongName { get; set; }
        public string SongIndex { get; set; }
        public string Genre { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Year { get; set; }
        public string Artists { get; set; }
    }
}
